default_platform(:ios)

platform :ios do

  desc "Runs app unit tests"

  lane :tests do
     
     run_tests(
        project: "./MockApp.xcodeproj",
        devices: ["iPhone 14"]
     )

  end

end
